config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  get '/places',to: "places#bulk_create"
  resources :flights, only: %i[index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
# app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :places
  has_many :flights
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @places = Place.all
    @flights = flight_params ? fetch_flights : []

    # Caso: entrar en /flights sin busqueda 
    # Tira error
    # Solución:
    # Prevenir resultado Nil para @flights
   
    unless @flights != NilClass
      @origin = @flights.Places[0]["Name"]
      @destination = @flights.Places[1]["Name"]
    end
  end

  private

  def flight_params
    params.permit(:outboundpartialdate, :destinationplace, :originplace)
  end

  # Metodos como este hay que guardar dentro de un Service o una clase ruby
  # Porque?
  # 1) Es probable que un request a API lo utilizarias en otros lados de tu App
  # 2) Evitas que tu controlador se convierta en un FAT Controller (código mas limpio y legible)
  def fetch_flights
    params["flight"].class == NilClass ? date = "#{Date.today}" : date = params["flight"]["outboundpartialdate"]
    response = Unirest.get "https://skyscanner-skyscanner-flight-search-v1.p.rapidapi.com/apiservices/browseroutes/v1.0/US/USD/en-US/SFO-sky/ORD-sky/#{date}",
   
    headers:{
      "X-RapidAPI-Host" => "skyscanner-skyscanner-flight-search-v1.p.rapidapi.com",
      "X-RapidAPI-Key" => "dd277984c2mshb0dba71490fe32fp140ff3jsnbfdc27271a52",
      "Accept": "application/json",
      "Content-Type": "application/json"
    }
    JSON.parse(response.body.to_json, object_class: OpenStruct)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end

end

app/controllers/places_controller.rb
require 'unirest'

class PlacesController < ApplicationController

  def bulk_create
    Place.destroy_all
    @places = fetch_places
    @user = current_user
    @places.each do |place|
      new_place = Place.new(
        place_id: place.PlaceId,
        place: place.PlaceName,
        country_id: place.CountryId,
        region_id: place.RegionId,
        city_id: place.CityId,
        country: place.CountryName,
      )
      new_place.user_id = @user.id
      new_place.save!
    end
    # raise
    redirect_to root_path
  end

  private

  def fetch_places
    response = Unirest.get "https://skyscanner-skyscanner-flight-search-v1.p.rapidapi.com/apiservices/autosuggest/v1.0/UK/GBP/en-GB/?query=florida",
    headers:{
      "X-RapidAPI-Host" =>  "skyscanner-skyscanner-flight-search-v1.p.rapidapi.com",
      "X-RapidAPI-Key" => "dd277984c2mshb0dba71490fe32fp140ff3jsnbfdc27271a52",
      "Accept": "application/json",
      "Content-Type": "application/json"
    },
    parameters:{
      "country" => "US",
      "currency" => "USD",
      "locale" => "en-US"
    }
    JSON.parse(response.body.to_json, object_class: OpenStruct).Places
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/flights/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-12 col-md-8 offset-md-2 card my-3">
        <h2 class="agregar-gasto my-3">Buscar vuelos</h2>
        <div class= "form-group" >
          <%= form_for :flight, method: :get do |f|%>
            <%= f.label :date %>:
            <%= f.date_field :outboundpartialdate, class:"form-control" %><br />
            <%= f.label :origin %>:
            <%= f.collection_select :originplace, @places, :place_id, :place_id, class:"form-control form-control-lg"%><br />
            <%= f.label :destination %>:
            <%= f.collection_select :destinationplace, @places, :place_id, :place_id, class:"form-control form-control-lg"%><br />
            <%= f.submit "Buscar", class: "btn btn-success" %>
          <% end %>
        </div>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-md-6" >
      <% if @flights.class == NilClass %>
        <h1>Busca nuevos vuelos!</h1>
      <% else %>
        <ul>
          <% @flights.Quotes.first(20).each do |flight| %>
            <li class="card m-2 p-4">
              Precio : USD <%= flight.MinPrice.round %> - 
              <%= flight.Direct == true ? "Vuelo directo" : "Vuelo con escalas" %> -
              Origen: <%=@origin%> -
              Destino: <%=@destination%>
            </li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<h1>Hola!</h1>


<%=link_to "Search Places", places_path, class:'btn btn-primary'%>
<% if Place.present? %>
    
<%=link_to "Search Flights", flights_path, class:'btn btn-primary'%>
<% end %>
<%=console%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PowExample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://img2.pngio.com/skyscannerpng-skyscanner-png-1222_692.png" %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "/assets/avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>